apiVersion: apps/v1
kind: Deployment
metadata:
  name: PaymentContext
  labels:
    app: PaymentContext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PaymentContext
  template:
    metadata:
      labels:
        app: PaymentContext
    spec:
      containers:
        - name: PaymentContext
          image: username/PaymentContext:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5